name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Windows,  os: windows-2022 }
          - { name: Linux,    os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
          - { name: macOS,    os: macos-latest }

    steps:
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev --no-install-recommends -y

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        shell: bash
        run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=install ${{matrix.platform.flags}} -DBUILD_SHARED_LIBS=FALSE

      - name: Build
        shell: bash
        run: cmake --build build --config Release

      - name: Zip build
        shell: bash
        run: (cd build/bin && zip -r ../../${{matrix.platform.name}}.zip .)

      - name: Upload artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ./${{matrix.platform.name}}.zip
